server:
  port: 7070
  tomcat:
    relaxed-path-chars: '<,>,[,],^,`'
    relaxed-query-chars: '<,>,[,],],^,`'
    reject-illegal-header: true
spring:
  application:
    name: realtech
  jpa.open-in-view: false
  datasource:
    jdbcUrl: jdbc:log4jdbc:mariadb://52.78.159.98:3306/realtech
    username: realtech
    password: tv1234
    driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    connectionTimeout: 58000
    maxLifetime: 580000
    maximumPoolSize: 20
    #leakDetectionThreshold: 20000
  data:
    jpa:
      repositories:
        bootstrap-mode: default # deferred, default, lazy - https://velog.io/@daoh98/SpringJPA-Redis-Repository-scan-%EB%AC%B8%EC%A0%9C
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      max-file-size: 5MB    # 파일 하나의 최대 크기
      max-request-size: 10MB # 요청 전체의 최대 크기

#  session:
#    store-type: redis

aws:
  access-key-id: AKIA2NOJF4NQEFLYAN7X
  secret-access-key: 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
  